# Generated by Django 5.0.4 on 2024-05-05 23:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='rayos_X',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(default=datetime.datetime(2024, 5, 5, 23, 17, 53, 428520, tzinfo=datetime.timezone.utc))),
                ('bloque_horas', models.TimeField(default=datetime.time(8, 0))),
                ('posible_diagnostico', models.TextField(blank=True)),
                ('medico_deriva', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
