# Generated by Django 5.0.4 on 2024-05-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rayos_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='rayos_x',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
