# Generated by Django 5.0.4 on 2024-05-05 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rayos_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rayos_x',
            name='fecha_reserva',
            field=models.DateField(default=datetime.datetime(2024, 5, 5, 23, 18, 9, 305007, tzinfo=datetime.timezone.utc)),
        ),
    ]
