# Generated by Django 5.0.4 on 2024-05-06 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_rayos_x_fecha_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rayos_x',
            name='fecha_reserva',
            field=models.DateField(default=datetime.datetime(2024, 5, 6, 0, 50, 25, 331628, tzinfo=datetime.timezone.utc)),
        ),
    ]
