# Generated by Django 5.0.4 on 2024-05-06 20:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_rayos_x_fecha_reserva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rayos_x',
            name='tipo_de_examen',
            field=models.CharField(choices=[('Rayos X', 'Rayos X')], default='Rayos X', max_length=100),
        ),
        migrations.AlterField(
            model_name='rayos_x',
            name='fecha_reserva',
            field=models.DateField(default=datetime.datetime(2024, 5, 6, 20, 13, 30, 247582, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ecografias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(default=datetime.datetime(2024, 5, 6, 20, 13, 30, 249611, tzinfo=datetime.timezone.utc))),
                ('bloque_horas', models.TimeField(default=datetime.time(8, 0))),
                ('posible_diagnostico', models.TextField(blank=True)),
                ('medico_deriva', models.CharField(max_length=100)),
                ('tipo_de_examen', models.CharField(choices=[('Ecografías', 'Ecografías')], default='Ecografías', max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='resonancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(default=datetime.datetime(2024, 5, 6, 20, 13, 30, 251974, tzinfo=datetime.timezone.utc))),
                ('bloque_horas', models.TimeField(default=datetime.time(8, 0))),
                ('posible_diagnostico', models.TextField(blank=True)),
                ('medico_deriva', models.CharField(max_length=100)),
                ('tipo_de_examen', models.CharField(choices=[('Resonancia Magnética', 'Resonancia Magnética')], default='Resonancia Magnética', max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tomografias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(default=datetime.datetime(2024, 5, 6, 20, 13, 30, 250612, tzinfo=datetime.timezone.utc))),
                ('bloque_horas', models.TimeField(default=datetime.time(8, 0))),
                ('posible_diagnostico', models.TextField(blank=True)),
                ('medico_deriva', models.CharField(max_length=100)),
                ('tipo_de_examen', models.CharField(choices=[('Tomografías', 'Tomografías')], default='Tomografías', max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
