# Generated by Django 5.0.4 on 2024-05-06 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profile_alergias_profile_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecografias',
            name='fecha_reserva',
            field=models.DateField(default=datetime.datetime(2024, 5, 6, 21, 50, 45, 728739, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rayos_x',
            name='fecha_reserva',
            field=models.DateField(default=datetime.datetime(2024, 5, 6, 21, 50, 45, 728739, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resonancias',
            name='fecha_reserva',
            field=models.DateField(default=datetime.datetime(2024, 5, 6, 21, 50, 45, 729740, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tomografias',
            name='fecha_reserva',
            field=models.DateField(default=datetime.datetime(2024, 5, 6, 21, 50, 45, 729740, tzinfo=datetime.timezone.utc)),
        ),
    ]
