# Generated by Django 5.0.4 on 2024-05-07 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_ecografias_fecha_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecografias',
            name='fecha_reserva',
            field=models.DateField(default=datetime.datetime(2024, 5, 7, 1, 45, 29, 351553, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rayos_x',
            name='fecha_reserva',
            field=models.DateField(default=datetime.datetime(2024, 5, 7, 1, 45, 29, 349801, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resonancias',
            name='fecha_reserva',
            field=models.DateField(default=datetime.datetime(2024, 5, 7, 1, 45, 29, 353552, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tomografias',
            name='fecha_reserva',
            field=models.DateField(default=datetime.datetime(2024, 5, 7, 1, 45, 29, 353050, tzinfo=datetime.timezone.utc)),
        ),
    ]
